### API CONCESSIONÁRIAS - GET

GET http://localhost:8080/api/v1/concessionarias

### API CONCESSIONÁRIAS - POST

POST http://localhost:8080/api/v1/concessionarias
Content-Type: application/json

{
    "nome": "Zimbas Concessionária",
    "endereco": "Rua Itajuba, 210",
    "telefone": "3344-2211",
    "email": "contato@zimbasconecessionaria.com"
}

### API CONCESSIONÁRIAS - PUT

PUT http://localhost:8080/api/v1/concessionarias/2
Content-Type: application/json

{
    "id": 1,
    "nome": "Zimbas New Concessionária",
    "endereco": "Rua Itajuba, 210",
    "telefone": "3344-2211",
    "email": "contato@zimbasconecessionaria.com"
}

### API CONCESSIONÁRIAS - DELETE

DELETE http://localhost:8080/api/v1/concessionarias/2
Content-Type: application/json