### API FUNCIONÁRIOS - GET

GET http://localhost:8080/api/v1/funcionarios

### API FUNCIONÁRIOS - POST

POST http://localhost:8080/api/v1/funcionarios
Content-Type: application/json

{
    "nome": "Caua Richard",
    "posicao": "Vendedor",
    "concessionaria": {
        "id": 1,
        "nome": "Zimbas Concessionaria",
        "funcionarios": null
  }
}

### API FUNCIONÁRIOS - PUT

PUT http://localhost:8080/api/v1/funcionarios/2
Content-Type: application/json

{
  "id": 1,
  "nome": "Caua Richard",
  "posicao": "Vendedor",
  "concessionaria": {
    "id": 1,
    "nome": "Zimbas Concessionaria",
    "funcionarios": null
  }
}


### API FUNCIONÁRIOS - DELETE

DELETE http://localhost:8080/api/v1/funcionarios/2
Content-Type: application/json
